<?php
declare(strict_types=1);
ob_start();
$selectedCount = count(array_filter($items, static fn (array $item): bool => ($item['selected'] ?? false) === true && ($item['available'] ?? false) === true));
$selectableItems = array_values(array_filter($items, static fn (array $item): bool => ($item['available'] ?? false) === true));
$allSelected = $selectableItems !== [] && count(array_filter($selectableItems, static fn (array $item): bool => ($item['selected'] ?? false) === true)) === count($selectableItems);
?>
<div class="container breadcrumb-line"><a href="/">Trang chủ</a><i class="fa-solid fa-chevron-right"></i><span>Giỏ hàng</span></div>
<section class="container cart-section"><div class="section-heading"><div><span class="eyebrow">LỰA CHỌN CỦA BẠN</span><h1>Giỏ hàng</h1><p class="muted mb-0"><?= (int) $lineCount ?> dòng sản phẩm</p></div><a class="text-link" href="/#shop-area">Tiếp tục mua sắm <i class="fa-solid fa-arrow-right"></i></a></div>
<?php if (is_array($flash) && isset($flash['message'])): ?><div class="alert alert-<?= h($flash['type'] ?? 'info') ?> py-2" role="status"><?= h($flash['message']) ?></div><?php endif; ?>
<?php if ($items === []): ?><div class="cart-empty"><i class="fa-solid fa-bag-shopping"></i><h2>Giỏ hàng đang trống</h2><p>Chọn một sản phẩm bạn yêu thích để bắt đầu.</p><a class="btn btn-dark rounded-pill px-4" href="/#shop-area">Khám phá sản phẩm</a></div><?php else: ?>
<div class="row g-4 align-items-start"><div class="col-lg-8"><div class="cart-table-wrap"><table class="table cart-table align-middle mb-0"><thead><tr><th><form action="/cart/items/select-all" method="post" class="m-0"><input type="hidden" name="csrf_token" value="<?= h(csrfToken()) ?>"><input class="form-check-input" type="checkbox" name="selected" value="1" <?= $allSelected ? 'checked' : '' ?> <?= $selectableItems === [] ? 'disabled' : '' ?> onchange="this.form.submit()" aria-label="Chọn tất cả sản phẩm"></form></th><th>Sản phẩm</th><th>Kích thước</th><th>Đơn giá</th><th>Số lượng</th><th></th></tr></thead><tbody>
<?php foreach ($items as $item): ?><tr class="<?= $item['available'] ? '' : 'cart-item-unavailable' ?>"><td><form action="/cart/items/select" method="post"><input type="hidden" name="csrf_token" value="<?= h(csrfToken()) ?>"><input type="hidden" name="variant_id" value="<?= h($item['variant_id']) ?>"><input class="form-check-input" type="checkbox" name="selected" value="1" <?= $item['selected'] && $item['available'] ? 'checked' : '' ?> <?= $item['available'] ? '' : 'disabled' ?> aria-label="Chọn <?= h($item['name']) ?>"><button class="btn btn-link btn-sm p-0 selection-save" type="submit">Lưu</button></form></td>
<td><div class="cart-product"><a href="/products/<?= rawurlencode($item['product_id']) ?>"><img src="/<?= h($item['image']) ?>" alt="<?= h($item['name']) ?>"></a><div><a href="/products/<?= rawurlencode($item['product_id']) ?>" class="cart-product-name"><?= h($item['name']) ?></a><?php if (!$item['available']): ?><small class="text-danger d-block">Biến thể không còn khả dụng</small><?php endif; ?></div></div></td>
<td><?php if ($item['available']): ?><form action="/cart/items/change-size" method="post" class="cart-inline-form"><input type="hidden" name="csrf_token" value="<?= h(csrfToken()) ?>"><input type="hidden" name="old_variant_id" value="<?= h($item['variant_id']) ?>"><select class="form-select form-select-sm" name="new_variant_id" onchange="this.form.submit()" aria-label="Đổi kích thước"><?php foreach ($item['variants'] as $variant): ?><option value="<?= h($variant['variant_id']) ?>" <?= $variant['variant_id'] === $item['variant_id'] ? 'selected' : '' ?> <?= ((int) $variant['stock'] < (int) $item['quantity'] && $variant['variant_id'] !== $item['variant_id']) ? 'disabled' : '' ?>><?= h($variant['size']) ?></option><?php endforeach; ?></select></form><?php else: ?><span class="muted">—</span><?php endif; ?></td>
<td class="cart-price"><?= money($item['unit_price']) ?></td><td><?php if ($item['available']): ?><form action="/cart/items/update" method="post" class="cart-inline-form quantity-form"><input type="hidden" name="csrf_token" value="<?= h(csrfToken()) ?>"><input type="hidden" name="variant_id" value="<?= h($item['variant_id']) ?>"><input class="form-control form-control-sm" type="number" name="quantity" value="<?= (int) $item['quantity'] ?>" min="1" max="<?= (int) $item['stock'] ?>" aria-label="Số lượng"><button class="btn btn-sm btn-outline-dark" type="submit">Cập nhật</button></form><?php else: ?><span><?= (int) $item['quantity'] ?></span><?php endif; ?></td>
<td><form action="/cart/items/remove" method="post"><input type="hidden" name="csrf_token" value="<?= h(csrfToken()) ?>"><input type="hidden" name="variant_id" value="<?= h($item['variant_id']) ?>"><button class="btn btn-link text-danger" type="submit" aria-label="Xóa <?= h($item['name']) ?>"><i class="fa-regular fa-trash-can"></i></button></form></td></tr><?php endforeach; ?>
</tbody></table></div></div><div class="col-lg-4"><aside class="cart-summary"><h2>Tóm tắt giỏ hàng</h2><div class="summary-row"><span>Sản phẩm đã chọn</span><strong><?= $selectedCount ?></strong></div><div class="summary-row summary-total"><span>Tạm tính</span><strong><?= money($subtotal) ?></strong></div><p class="cart-checkout-note">Giá và tồn kho được kiểm tra lại ở bước thanh toán.</p><?php if ($selectedCount > 0): ?><a class="btn btn-dark w-100 rounded-pill" href="/checkout">Tiến hành thanh toán</a><?php else: ?><button class="btn btn-dark w-100 rounded-pill" type="button" disabled>Chọn sản phẩm để thanh toán</button><?php endif; ?><a class="continue-link" href="/#shop-area">Tiếp tục mua sắm</a></aside></div></div>
<?php endif; ?></section>
<?php
$content = (string) ob_get_clean();
require dirname(__DIR__) . '/layout.php';
