<?php declare(strict_types=1); ob_start(); $isEdit = is_array($product); $defaultVariants = $isEdit ? ($product['variants'] ?? []) : [['variant_id' => '', 'size' => 'S', 'price' => 0, 'stock' => 10, 'active' => true]]; $variantJson = $oldInput['variants_json'] ?? json_encode($defaultVariants, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES); ?>
<div class="container breadcrumb-line"><a href="/">Trang chủ</a><i class="fa-solid fa-chevron-right"></i><a href="/admin/products">Quản lý sản phẩm</a><i class="fa-solid fa-chevron-right"></i><span><?= $isEdit ? 'Sửa sản phẩm' : 'Thêm sản phẩm' ?></span></div>
<section class="container orders-section"><div class="section-heading"><div><span class="eyebrow">KHU VỰC QUẢN TRỊ</span><h1><?= $isEdit ? 'Sửa sản phẩm ' . h($product['legacy_id'] ?? '') : 'Thêm sản phẩm' ?></h1><p class="muted mb-0">Giá và tồn kho được nhập theo từng size.</p></div></div>
<?php if (is_string($error ?? null)): ?><div class="alert alert-danger" role="alert"><?= h($error) ?></div><?php endif; ?>
<?php if (($user = currentUser()) !== null && ($user['role'] ?? '') !== 'manager'): ?><div class="alert alert-info">Bạn có quyền xem sản phẩm; chỉ quản lý mới được lưu thay đổi.</div><?php else: ?>
<form action="<?= $isEdit ? '/admin/products/' . rawurlencode((string) $product['legacy_id']) . '/edit' : '/admin/products/new' ?>" method="post" enctype="multipart/form-data" class="row g-3"><input type="hidden" name="csrf_token" value="<?= h(csrfToken()) ?>">
<div class="col-md-8"><label class="form-label" for="productName">Tên sản phẩm</label><input class="form-control" id="productName" name="name" maxlength="160" required value="<?= h($oldInput['name'] ?? ($product['name'] ?? '')) ?>"></div>
<div class="col-md-4"><label class="form-label" for="categoryCode">Danh mục</label><?php $category = (string) ($oldInput['category_code'] ?? ($product['category']['code'] ?? 'A')); ?><select class="form-select" id="categoryCode" name="category_code" required><?php foreach (['A' => 'Áo', 'Q' => 'Quần', 'G' => 'Giày'] as $code => $label): ?><option value="<?= h($code) ?>" <?= $category === $code ? 'selected' : '' ?>><?= h($label) ?></option><?php endforeach; ?></select></div>
<div class="col-12"><label class="form-label" for="productDescription">Mô tả</label><textarea class="form-control" id="productDescription" name="description" rows="5" maxlength="5000"><?= h($oldInput['description'] ?? ($product['description'] ?? '')) ?></textarea></div>
<div class="col-12"><label class="form-label" for="productImage">Ảnh sản phẩm (JPEG, PNG hoặc WebP; tối đa 5 MB)</label><input class="form-control" type="file" id="productImage" name="image" accept="image/jpeg,image/png,image/webp"><div class="form-text">Ảnh được kiểm tra nội dung, kích thước và lưu ngoài thư mục public. Ảnh cũ vẫn được giữ; ảnh mới sẽ trở thành ảnh chính.</div><?php if ($isEdit): ?><div class="mt-2"><img src="/<?= h(productImage($product)) ?>" alt="Ảnh hiện tại" style="max-width:180px;max-height:180px;object-fit:cover"></div><?php endif; ?></div>
<div class="col-12"><label class="form-label" for="variantsJson">Biến thể (JSON)</label><textarea class="form-control font-monospace" id="variantsJson" name="variants_json" rows="15" required><?= h(is_string($variantJson) ? $variantJson : '[]') ?></textarea><div class="form-text">Mỗi dòng gồm <code>variant_id</code>, <code>size</code>, <code>price</code>, <code>stock</code>, <code>active</code>. Với sản phẩm mới, để variant_id rỗng; hệ thống tự tạo mã. Khi sửa, giữ nguyên mã và size cũ. Để ngừng bán một size, đặt active thành false; không xóa biến thể lịch sử.</div></div>
<div class="col-12 d-flex gap-2"><button class="btn btn-dark rounded-pill" type="submit">Lưu sản phẩm</button><a class="btn btn-outline-secondary rounded-pill" href="/admin/products">Hủy</a></div></form><?php endif; ?></section>
<?php $content = (string) ob_get_clean(); require dirname(__DIR__, 2) . '/layout.php';
