<?php
declare(strict_types=1);
ob_start();
$images = $product['images'] ?? [];
?>
<div class="container breadcrumb-line"><a href="/">Trang chủ</a><i class="fa-solid fa-chevron-right"></i><a href="/#shop-area">Sản phẩm</a><i class="fa-solid fa-chevron-right"></i><span><?= h($product['name'] ?? '') ?></span></div>
<section class="container detail-section"><div class="row g-4 g-lg-5">
    <div class="col-lg-6"><div class="detail-main-image"><img id="mainProductImage" src="/<?= h(productImage($product)) ?>" alt="<?= h($product['name'] ?? '') ?>"></div><div class="detail-thumbnails" role="list"><?php foreach ($images as $index => $image): ?><button class="thumb-button <?= $index === 0 ? 'active' : '' ?>" type="button" data-image="/<?= h($image['path'] ?? '') ?>" aria-label="Xem ảnh <?= $index + 1 ?>"><img src="/<?= h($image['path'] ?? '') ?>" alt=""></button><?php endforeach; ?></div></div>
    <div class="col-lg-6 detail-copy"><span class="eyebrow"><?= h($product['category']['name'] ?? 'Sản phẩm') ?> · <?= h($product['legacy_id'] ?? '') ?></span><h1><?= h($product['name'] ?? '') ?></h1><div class="rating-line detail-rating"><span class="stars"><i class="fa-solid fa-star"></i> <?= number_format((float) $product['rating_average'], 1, ',', '.') ?></span><a href="#review-area"><?= (int) $product['rating_count'] ?> đánh giá</a></div><div class="detail-price"><?= money($product['display_price'] ?? 0) ?></div><p class="detail-description"><?= nl2br(h($product['description'] ?? '')) ?></p>
        <div class="variant-heading">Kích thước có sẵn</div><div class="variant-list"><?php if ($product['variants'] === []): ?><span class="muted">Hiện chưa có biến thể.</span><?php else: foreach ($product['variants'] as $variant): ?><div class="variant-chip"><strong><?= h($variant['size'] ?? '') ?></strong><span><?= money($variant['price'] ?? 0) ?></span><?php if ((int) ($variant['stock'] ?? 0) < 1): ?><small>Hết hàng</small><?php else: ?><small>Còn <?= (int) $variant['stock'] ?></small><?php endif; ?></div><?php endforeach; endif; ?></div>
        <?php $availableVariants = array_values(array_filter($product['variants'], static fn (array $variant): bool => (int) ($variant['stock'] ?? 0) > 0)); ?>
        <?php if ($availableVariants !== []): ?><form class="add-to-cart-form" action="/cart/items/add" method="post"><input type="hidden" name="csrf_token" value="<?= h(csrfToken()) ?>"><input type="hidden" name="product_id" value="<?= h($product['legacy_id']) ?>"><label class="variant-heading" for="variant_id">Chọn kích thước</label><div class="d-flex flex-wrap gap-2"><select class="form-select size-select" id="variant_id" name="variant_id" required><?php foreach ($availableVariants as $variant): ?><option value="<?= h($variant['variant_id']) ?>" data-stock="<?= (int) $variant['stock'] ?>"><?= h($variant['size']) ?> · <?= money($variant['price']) ?> (còn <?= (int) $variant['stock'] ?>)</option><?php endforeach; ?></select><div class="input-group quantity-select"><button class="btn btn-outline-secondary" type="button" data-quantity-step="-1" aria-label="Giảm">−</button><input class="form-control text-center" type="number" name="quantity" value="1" min="1" max="<?= (int) $availableVariants[0]['stock'] ?>" required><button class="btn btn-outline-secondary" type="button" data-quantity-step="1" aria-label="Tăng">+</button></div><button class="btn btn-dark add-cart-button" type="submit"><i class="fa-solid fa-bag-shopping me-2"></i>Thêm vào giỏ</button></div></form><?php else: ?><div class="alert alert-secondary mt-4">Sản phẩm hiện đã hết hàng.</div><?php endif; ?>
        <div class="detail-note"><i class="fa-solid fa-box-open"></i><span>Thông tin giá và kích thước được lấy trực tiếp từ dữ liệu sản phẩm.</span></div>
    </div>
</div></section>
<section id="review-area" class="review-section"><div class="container"><div class="section-heading"><div><span class="eyebrow">CHIA SẺ TỪ KHÁCH HÀNG</span><h2>Đánh giá sản phẩm</h2></div><span class="review-summary"><i class="fa-solid fa-star"></i> <?= number_format((float) $product['rating_average'], 1, ',', '.') ?> / 5 · <?= count($reviews) ?> đánh giá</span></div>
<?php if (is_array($reviewFlash) && isset($reviewFlash['message'])): ?><div class="alert alert-<?= h($reviewFlash['type'] ?? 'info') ?>" role="status"><?= h($reviewFlash['message']) ?></div><?php endif; ?>
<form class="review-submit-form" action="/products/<?= rawurlencode((string) $product['legacy_id']) ?>/reviews" method="post"><input type="hidden" name="csrf_token" value="<?= h(csrfToken()) ?>"><?php $reviewer = currentUser(); ?><?php if (($reviewer['type'] ?? null) === 'customer'): ?><p class="review-account-note">Đánh giá với tên <strong><?= h($reviewer['name'] ?: $reviewer['username']) ?></strong></p><?php else: ?><label for="reviewerName">Tên của bạn</label><input class="form-control" id="reviewerName" name="reviewer_name" maxlength="100" required><?php endif; ?><label for="reviewRating">Số sao</label><select class="form-select" id="reviewRating" name="rating" required><?php for ($star = 5; $star >= 1; --$star): ?><option value="<?= $star ?>" <?= $star === 5 ? 'selected' : '' ?>><?= $star ?> sao</option><?php endfor; ?></select><label for="reviewContent">Nội dung đánh giá</label><textarea class="form-control" id="reviewContent" name="content" rows="4" maxlength="2000" required></textarea><button class="btn btn-dark rounded-pill" type="submit">Gửi đánh giá</button><small class="muted">Mỗi tài khoản hoặc phiên khách có thể đánh giá sản phẩm này một lần.</small></form>
<?php if ($reviews === []): ?><p class="muted">Sản phẩm chưa có đánh giá.</p><?php else: ?><div class="row g-3"><?php foreach ($reviews as $review): ?><div class="col-md-6"><article class="review-card"><div class="d-flex justify-content-between gap-2"><strong><?= h($review['reviewer_name'] ?? 'Khách hàng') ?></strong><span class="stars"><?php for ($star = 1; $star <= 5; ++$star): ?><i class="fa-<?= $star <= (int) ($review['rating'] ?? 0) ? 'solid' : 'regular' ?> fa-star"></i><?php endfor; ?></span></div><p><?= nl2br(h($review['content'] ?? '')) ?></p><?php if (is_array($review['admin_response'] ?? null) && is_string($review['admin_response']['content'] ?? null)): ?><div class="alert alert-light border mt-3 mb-0"><strong>Phản hồi từ cửa hàng · <?= h($review['admin_response']['staff_name'] ?? 'Nhân viên') ?></strong><p class="mb-0 mt-2"><?= nl2br(h($review['admin_response']['content'])) ?></p></div><?php endif; ?></article></div><?php endforeach; ?></div><?php endif; ?>
</div></section>
<?php if ($related !== []): ?><section class="container section-block"><div class="section-heading"><div><span class="eyebrow">CÙNG DANH MỤC</span><h2>Sản phẩm liên quan</h2></div></div><div class="row g-3 g-lg-4"><?php foreach ($related as $item): ?><div class="col-6 col-md-3"><?php require __DIR__ . '/product-card.php'; ?></div><?php endforeach; ?></div></section><?php endif; ?>
<?php
$content = (string) ob_get_clean();
require dirname(__DIR__) . '/layout.php';
